web: gunicorn professional_network.wsgi:application --config gunicorn.conf.py
worker: daphne -b 0.0.0.0 -p $PORT professional_network.asgi:application
release: python manage.py migrate --noinput && python manage.py collectstatic --noinput
