# Generated by Django 5.2.10 on 2026-01-29 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('messaging', '0003_queuedmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('connection_rejected', 'Connection Rejected'), ('new_message', 'New Message'), ('message_delivered', 'Message Delivered'), ('message_read', 'Message Read'), ('job_application', 'Job Application Received'), ('application_status', 'Application Status Update'), ('new_job_posted', 'New Job Posted'), ('post_liked', 'Post Liked'), ('post_commented', 'Post Commented'), ('post_shared', 'Post Shared'), ('mention', 'Mentioned in Post'), ('new_follower', 'New Follower'), ('follow_accepted', 'Follow Request Accepted'), ('system_announcement', 'System Announcement'), ('security_alert', 'Security Alert')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_key', models.CharField(blank=True, help_text='Key for grouping similar notifications', max_length=255, null=True)),
                ('is_grouped', models.BooleanField(default=False)),
                ('group_count', models.IntegerField(default=1, help_text='Number of notifications in this group')),
                ('action_url', models.URLField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='messaging_n_recipie_0f301b_idx'), models.Index(fields=['recipient', 'is_read'], name='messaging_n_recipie_b24bf9_idx'), models.Index(fields=['recipient', 'notification_type'], name='messaging_n_recipie_fd4d20_idx'), models.Index(fields=['group_key'], name='messaging_n_group_k_f57ea6_idx'), models.Index(fields=['created_at'], name='messaging_n_created_a9b879_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('connection_rejected', 'Connection Rejected'), ('new_message', 'New Message'), ('message_delivered', 'Message Delivered'), ('message_read', 'Message Read'), ('job_application', 'Job Application Received'), ('application_status', 'Application Status Update'), ('new_job_posted', 'New Job Posted'), ('post_liked', 'Post Liked'), ('post_commented', 'Post Commented'), ('post_shared', 'Post Shared'), ('mention', 'Mentioned in Post'), ('new_follower', 'New Follower'), ('follow_accepted', 'Follow Request Accepted'), ('system_announcement', 'System Announcement'), ('security_alert', 'Security Alert')], max_length=50)),
                ('delivery_method', models.CharField(choices=[('realtime', 'Real-time WebSocket'), ('email', 'Email'), ('push', 'Push Notification'), ('none', 'Disabled')], default='realtime', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no notifications)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'notification_type'], name='messaging_n_user_id_a7c367_idx')],
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
