# Generated by Django 5.2.10 on 2026-01-29 19:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_notification_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='Attach a file (max 10MB, images and documents only)', null=True, upload_to=core.validators.get_upload_path, validators=[core.validators.AttachmentUploadValidator()]),
        ),
    ]
