# Generated by Django 5.2.10 on 2026-02-05 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_message_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_typing', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='queuedmessage',
            options={'ordering': ['priority', 'created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='client_id',
            field=models.CharField(blank=True, help_text='Client-side message ID for deduplication', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='queuedmessage',
            name='backoff_multiplier',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='queuedmessage',
            name='base_delay_seconds',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='queuedmessage',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='queuedmessage',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuedmessage',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuedmessage',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='queuedmessage',
            name='max_delay_seconds',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='queuedmessage',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuedmessage',
            name='original_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuedmessage',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Normal'), (3, 'Low')], default=2),
        ),
        migrations.AddField(
            model_name='queuedmessage',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuedmessage',
            name='queue_type',
            field=models.CharField(choices=[('outgoing', 'Outgoing'), ('incoming', 'Incoming'), ('retry', 'Retry')], default='outgoing', max_length=20),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='active_connections',
            field=models.IntegerField(default=0, help_text='Number of active WebSocket connections'),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='connection_id',
            field=models.CharField(blank=True, help_text='Current connection identifier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='device_info',
            field=models.JSONField(blank=True, default=dict, help_text='Device and browser information'),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='last_ping',
            field=models.DateTimeField(blank=True, help_text='Last heartbeat ping timestamp', null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', 'created_at'], name='messaging_m_status_17edaf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_id'], name='messaging_m_client__c83394_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'status'], name='messaging_m_sender__ae6db4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'status'], name='messaging_m_recipie_b42201_idx'),
        ),
        migrations.AddIndex(
            model_name='queuedmessage',
            index=models.Index(fields=['queue_type', 'is_processed'], name='messaging_q_queue_t_15f37d_idx'),
        ),
        migrations.AddIndex(
            model_name='queuedmessage',
            index=models.Index(fields=['next_retry_at'], name='messaging_q_next_re_38d02c_idx'),
        ),
        migrations.AddIndex(
            model_name='queuedmessage',
            index=models.Index(fields=['expires_at'], name='messaging_q_expires_5ba8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='queuedmessage',
            index=models.Index(fields=['priority', 'created_at'], name='messaging_q_priorit_7f483c_idx'),
        ),
        migrations.AddIndex(
            model_name='queuedmessage',
            index=models.Index(fields=['client_id'], name='messaging_q_client__20aea3_idx'),
        ),
        migrations.AddIndex(
            model_name='userstatus',
            index=models.Index(fields=['is_online', 'last_seen'], name='messaging_u_is_onli_3639e4_idx'),
        ),
        migrations.AddIndex(
            model_name='userstatus',
            index=models.Index(fields=['last_ping'], name='messaging_u_last_pi_a88c69_idx'),
        ),
        migrations.AddIndex(
            model_name='userstatus',
            index=models.Index(fields=['active_connections'], name='messaging_u_active__51e975_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('sender', 'client_id'), name='unique_client_message'),
        ),
        migrations.AddField(
            model_name='typingstatus',
            name='chat_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_typing_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typingstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='typingstatus',
            index=models.Index(fields=['user', 'chat_partner'], name='messaging_t_user_id_db5234_idx'),
        ),
        migrations.AddIndex(
            model_name='typingstatus',
            index=models.Index(fields=['is_typing', 'last_updated'], name='messaging_t_is_typi_44ad60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typingstatus',
            unique_together={('user', 'chat_partner')},
        ),
    ]
