# Generated by Django 5.2.10 on 2026-06-19 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_add_updated_at_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('async_context', 'Async Context Error'), ('json_serialization', 'JSON Serialization Error'), ('connection_handling', 'Connection Handling Error'), ('routing_pattern', 'Routing Pattern Error'), ('websocket_transmission', 'WebSocket Transmission Error'), ('database_operation', 'Database Operation Error'), ('notification_delivery', 'Notification Delivery Error'), ('message_processing', 'Message Processing Error')], max_length=50)),
                ('error_message', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User associated with the error, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['error_type', '-occurred_at'], name='messaging_m_error_t_5aa550_idx'), models.Index(fields=['severity', '-occurred_at'], name='messaging_m_severit_110f6d_idx'), models.Index(fields=['resolved', '-occurred_at'], name='messaging_m_resolve_30d088_idx'), models.Index(fields=['user', '-occurred_at'], name='messaging_m_user_id_a5bc3e_idx')],
            },
        ),
    ]
