# Generated by Django 5.2.10 on 2026-06-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_messagingerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Deleted for everyone — content/attachment cleared'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_deleted',
            field=models.BooleanField(default=False, help_text='Recipient deleted this message for themselves'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_deleted',
            field=models.BooleanField(default=False, help_text='Sender deleted this message for themselves'),
        ),
    ]
