# Generated by Django 5.2.10 on 2026-01-29 19:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_report_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (max 5MB, JPG/PNG/GIF/WebP only)', null=True, upload_to=core.validators.get_upload_path, validators=[core.validators.ImageUploadValidator()]),
        ),
    ]
