# Generated by Django 5.2.10 on 2026-06-20 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_github_profile_instagram_profile_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Website, LinkedIn, GitHub, Portfolio', max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
