# Generated by Django 5.2.10 on 2026-06-21 03:09

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Upload a cover photo (max 20MB, JPG/PNG/GIF/WebP only)', null=True, upload_to=core.validators.get_upload_path, validators=[core.validators.ImageUploadValidator(max_size=20971520)]),
        ),
    ]
