# Generated by Django 5.2.10 on 2026-06-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_status'),
        ('jobs', '0002_savedjob'),
    ]

    operations = [
    ]
