# Generated by Django 5.2.10 on 2026-06-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_merge_0002_application_status_0002_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjob',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
