# Generated by Django 5.2.10 on 2026-08-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='easy_apply',
            field=models.BooleanField(default=False, help_text='Enable quick one-click application'),
        ),
    ]
